workflows:
  distribution-workflow:
    name: Card-Hive App Store Production
    integrations:
      app_store_connect: Codemagic API Key
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      groups:
        - firebase
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mycardhive.trading
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          cd mycardhive_mobile
          flutter precache --ios
          flutter clean
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd mycardhive_mobile/ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
      - name: Build iOS IPA
        script: |
          cd mycardhive_mobile
          flutter build ipa --release --no-codesign
      - name: Code sign iOS IPA
        script: |
          # The --bundle-id flag tells the tool which profile to use from your "Signing Identities"
          xcode-project build-ipa \
            --workspace mycardhive_mobile/ios/Runner.xcworkspace \
            --scheme Runner \
            --bundle-id com.mycardhive.trading
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
