// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8e70S0vy6mA3rsXa4GaUkBVBrYOKm4g',
    appId: '1:874588730991:web:cc2dde93c12f8d12a7bf9a',
    messagingSenderId: '874588730991',
    projectId: 'card-hive-60d38',
    authDomain: 'card-hive-60d38.firebaseapp.com',
    storageBucket: 'card-hive-60d38.firebasestorage.app',
    measurementId: 'G-01P9L0DRXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO8e70S0vy6mA3rsXa4GaUkBVBrYOKm4g',
    appId: '1:874588730991:android:68e94e5d115e53aca7bf9a',
    messagingSenderId: '874588730991',
    projectId: 'card-hive-60d38',
    storageBucket: 'card-hive-60d38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO8e70S0vy6mA3rsXa4GaUkBVBrYOKm4g',
    appId: '1:874588730991:ios:c4c924b024f9f97fa7bf9a',
    messagingSenderId: '874588730991',
    projectId: 'card-hive-60d38',
    storageBucket: 'card-hive-60d38.firebasestorage.app',
    iosBundleId: 'com.mycardhive.trading',
  );
}
